-- Sample data for employees
-- Insert initial employee data

USE new_academic_erp;

INSERT INTO employee (id, name, email, title, department_id) VALUES
    (1, 'Alice Johnson', 'admin.head@university.edu', 'Admin Head', 1),
    (2, 'Bob Smith', 'admin.staff@university.edu', 'Admin Assistant', 1),
    (3, 'Charlie Brown', 'accounts.manager@university.edu', 'Accounts Manager', 2),
    (4, 'Eve Davis', 'accounts.clerk@university.edu', 'Accounts Clerk', 2),
    (5, 'Dr. Jane Miller', 'cs.prof@university.edu', 'Professor', 3),
    (6, 'John Wilson', 'cs.assist@university.edu', 'Teaching Assistant', 3),
    (7, 'Dr. Sarah White', 'ee.prof@university.edu', 'Professor', 4),
    (8, 'Chris Taylor', 'ee.assist@university.edu', 'Lab Assistant', 4),
    (9, 'Dr. Mark Green', 'civil.prof@university.edu', 'Professor', 5),
    (10, 'Linda Walker', 'civil.tech@university.edu', 'Technician', 5),
    (11, 'Dr. Emily Harris', 'me.engg.prof@university.edu', 'Professor', 6),
    (12, 'Oliver King', 'me.engg.tech@university.edu', 'Technician', 6),
    (13, 'Dr. Rachel Turner', 'bio.prof@university.edu', 'Professor', 7),
    (14, 'Lucas Scott', 'bio.lab@university.edu', 'Lab Assistant', 7),
    (15, 'Dr. Robert Lee', 'env.sci.prof@university.edu', 'Professor', 8),
    (16, 'Sophie Davis', 'env.sci.assist@university.edu', 'Teaching Assistant', 8),
    (17, 'Dr. William Harris', 'math.prof@university.edu', 'Professor', 9),
    (18, 'Ava Clark', 'math.assist@university.edu', 'Teaching Assistant', 9),
    (19, 'Dr. Daniel White', 'phy.prof@university.edu', 'Professor', 10),
    (20, 'Lily Lewis', 'phy.lab@university.edu', 'Lab Assistant', 10),
    (21, 'Dr. Jack Martinez', 'chem.prof@university.edu', 'Professor', 11),
    (22, 'Mason Taylor', 'chem.lab@university.edu', 'Lab Assistant', 11),
    (23, 'Dr. Sophia Adams', 'pharma.prof@university.edu', 'Professor', 12),
    (24, 'Benjamin Lee', 'pharma.assist@university.edu', 'Teaching Assistant', 12),
    (25, 'Dr. Olivia Walker', 'arch.prof@university.edu', 'Professor', 13),
    (26, 'Matthew Harris', 'arch.assist@university.edu', 'Teaching Assistant', 13),
    (27, 'Dr. Samuel King', 'law.prof@university.edu', 'Professor', 14),
    (28, 'Zoe Green', 'law.assist@university.edu', 'Teaching Assistant', 14),
    (29, 'Dr. Michael Clark', 'ba.prof@university.edu', 'Professor', 15),
    (30, 'Chloe Adams', 'ba.assist@university.edu', 'Teaching Assistant', 15),
    (31, 'Dr. Ethan Martinez', 'eco.prof@university.edu', 'Professor', 16),
    (32, 'Liam Robinson', 'eco.assist@university.edu', 'Teaching Assistant', 16),
    (33, 'Dr. Isabella Scott', 'soc.prof@university.edu', 'Professor', 17),
    (34, 'Emma White', 'soc.assist@university.edu', 'Teaching Assistant', 17),
    (35, 'Dr. James Walker', 'psy.prof@university.edu', 'Professor', 18),
    (36, 'Oliver Brown', 'psy.assist@university.edu', 'Teaching Assistant', 18),
    (37, 'Dr. Mia Davis', 'finearts.prof@university.edu', 'Professor', 19),
    (38, 'Ella Taylor', 'finearts.assist@university.edu', 'Teaching Assistant', 19),
    (39, 'Dr. Noah Harris', 'music.prof@university.edu', 'Professor', 20),
    (40, 'Mia Green', 'music.assist@university.edu', 'Teaching Assistant', 20);
